from colmasys.endpoints.auth import *
from colmasys.endpoints.dashboard import *
from colmasys.endpoints.crud.account import *
from colmasys.endpoints.crud.class_ import *
from colmasys.endpoints.crud.class_student import *
from colmasys.endpoints.crud.post import *
from colmasys.endpoints.crud.comment import *
from colmasys.endpoints.crud.vote import *
from colmasys.endpoints.crud.chat import *