from colmasys.endpoints.auth import *
from colmasys.endpoints.dashboard import *
from colmasys.endpoints.crud.professor import *
from colmasys.endpoints.crud.student import *
from colmasys.endpoints.crud.class_ import *
from colmasys.endpoints.crud.class_student import *
from colmasys.endpoints.crud.post import *
from colmasys.endpoints.crud.comment import *
from colmasys.endpoints.crud.vote import *
from colmasys.endpoints.crud.chat import *
from colmasys.endpoints.crud.club import *